import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ClientProvider from "./clientProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import TopBar from "@/app/navigation/topbar/TopBar";
import SpeedComponent from "@/app/navigation/speed/SpeedComponent";
const inter = Inter({ subsets: ["latin"] });
import "react-perfect-scrollbar/dist/css/styles.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/options";
import SlidingMenuConfig from "./navigation/sidebar/SlidingMenuConfig";
import fetcher from "@/lib/fetcher";

export const metadata: Metadata = {
  title: "Chata GJKT",
  description: "Generated by create next app",
};

const getUserTheme = async (id: string) => {
  const { data } = await fetcher(`/api/users/detail/${id}/theme`);

  return data;
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = (await getServerSession(authOptions)) as any;
  const theme = data?.user?.id
    ? await getUserTheme(data?.user?.id)
    : { theme: 1 };

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen">
          <ClientProvider theme={theme?.theme}>
            <TopBar />
            <SlidingMenuConfig />
            <SpeedComponent />
            <div className="sm:p-5 p-2 overflow-auto flex-grow">{children}</div>
          </ClientProvider>
          <ToastContainer />
        </div>
      </body>
    </html>
  );
}
