import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ClientProvider from "./clientProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import TopBar from "@/app/navigation/topbar/TopBar";
import SlidingMenu from "@/app/navigation/sidebar/SlidingMenu";
import SpeedComponent from "@/app/navigation/speed/SpeedComponent";
const inter = Inter({ subsets: ["latin"] });
import "react-perfect-scrollbar/dist/css/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen flex-col">
          <ClientProvider>
            <TopBar />
            <SlidingMenu />
            <SpeedComponent />
            <div className="p-5">{children}</div>
          </ClientProvider>
          <ToastContainer />
        </div>
      </body>
    </html>
  );
}
